/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonitorSerial.Gui;

/**
 *
 * @author fmaia
 */
public class GuiAjuda extends javax.swing.JFrame {

    /**
     * Creates new form GuiAjuda
     */
    public GuiAjuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAAjuda = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTAAjuda.setColumns(20);
        jTAAjuda.setRows(5);
        jScrollPane1.setViewportView(jTAAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String texto = 
            "\nPasso 01: Download dos arquivos\n" +
            "\n" +
            " \n" +
            "  Acesse o site http://jlog.org/rxtx.html ou  http://www.rxtx.org  e faça download dos arquivos rxtxSerial.dll,\n"
          + "librxtxSerial.so e RXTXcomm.jar.\n" +
            " \n" +
            "Obs.: Lembrando de que devemos fazer download dos arquivos de acordo a arquitetura do\n "
          + "sistema operacional 32-bits (x86) ou 64-bits (x64).\n" +
            " \n" +
            " \n" +
            "Passo 02: Instalação dos arquivos\n" +
            "\n" +
            " \n" +
            "Windows\n" +
            " \n" +
            "      Copie o arquivo rxtxSerial.dll para:\n"
          + "\n" +
            "C:\\Windows\\System32;\n" +
            "C:\\Windows\\SysWOW64 (caso sistema operacional 64-bits (x64)).\n"
          + "\n" +
            "Linux\n" +
            "\n" +
            "      Copie o arquivo librxtxSerial.so para: \n"
          + "\n"
          + " /usr/lib/ \n"
          + "exemplo: cp /home/Usuario/librxtxSerial.so /usr/lib/.\n"
          + "\n"
          + "\n"
          + "\nPasso 03: Construir Pasta do Programa\n"+
            "\n"+
            "\n"
          + "  Crie a pasta Monitor serial e dentro dela a pasta lib\n"
          + "  Na pasta lib adicione o arquivo RXTXcomm.jar\n"
          + "  Na pasta Monitor serial adicione o arquivo MonitorSerial.jar\n"
          + "  E de acordo com a versão do sistema operacional adicione o seguinte arquivo\n"
          + "  o arquivo librxtxSerial.so caso sejá linux ou rxtxSerial.dll caso sejá Windows\n";
        
        jTAAjuda.setEditable(false);
        jTAAjuda.setText(texto);
        jTAAjuda.getCaret().setDot(0);
        jScrollPane1.scrollRectToVisible(jTAAjuda.getVisibleRect() );
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAAjuda;
    // End of variables declaration//GEN-END:variables
}
