/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonitorSerial.Gui;

import MonitorSerial.Controle.ControleContadorPacotes;

/**
 *
 * @author fmaia
 */
public class GuiContadorPacote extends javax.swing.JFrame {
    
    private final ControleContadorPacotes controleContadorPacotes;
    
    /**
     * Creates new form GuiContadorPacote
     * @param controleContadorPacotes
     */
    public GuiContadorPacote(ControleContadorPacotes controleContadorPacotes) {
        this.controleContadorPacotes = controleContadorPacotes;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPContador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLRX = new javax.swing.JLabel();
        jLTX = new javax.swing.JLabel();
        jLReturned = new javax.swing.JLabel();

        setTitle("Contador de Pacotes");
        setLocationByPlatform(true);
        setResizable(false);

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPContador.setBorder(javax.swing.BorderFactory.createTitledBorder("Contador"));

        jLabel1.setText("RX:");

        jLabel2.setText("TX:");

        jLabel4.setText("returned:");

        jLRX.setText("0");

        jLTX.setText("0");

        jLReturned.setText("0");

        javax.swing.GroupLayout jPContadorLayout = new javax.swing.GroupLayout(jPContador);
        jPContador.setLayout(jPContadorLayout);
        jPContadorLayout.setHorizontalGroup(
            jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPContadorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)))
                .addGap(28, 28, 28)
                .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTX)
                    .addComponent(jLRX)
                    .addComponent(jLReturned))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPContadorLayout.setVerticalGroup(
            jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLRX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLTX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLReturned))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPContador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controleContadorPacotes.limparContagem();
        this.jLRX.setText("0");
        this.jLTX.setText("0");
        this.jLReturned.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLRX;
    private javax.swing.JLabel jLReturned;
    private javax.swing.JLabel jLTX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPContador;
    // End of variables declaration//GEN-END:variables

    public void setJLRXText(Long cont){
        this.jLRX.setText(cont.toString());
    }
    
    public void setJLTXText(Long cont){
        this.jLTX.setText(cont.toString());
    }
    
    public void setJLReturned(Long cont){
        this.jLReturned.setText(cont.toString());
    }


}
