/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonitorSerial.Gui;

import MonitorSerial.Controle.ControleMonitor;
import gnu.io.NoSuchPortException;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.util.TooManyListenersException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fmaia
 */
public class GuiGrafico extends javax.swing.JFrame {
    
    private String[] listaPortas = null;
    private Integer[] listaBaudrates;
    private ControleMonitor controleMonitor;
    
    /**
     * Creates new form GuiGrafico
     */
    public GuiGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAjuda = new javax.swing.JButton();
        jPGrafico = new javax.swing.JPanel();
        jCBPortas = new javax.swing.JComboBox<>();
        jCBBaudrates = new javax.swing.JComboBox<>();
        jToggleBConexao = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBAjuda.setText("Ajuda");
        jBAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAjudaActionPerformed(evt);
            }
        });

        jPGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder("Grafico"));

        javax.swing.GroupLayout jPGraficoLayout = new javax.swing.GroupLayout(jPGrafico);
        jPGrafico.setLayout(jPGraficoLayout);
        jPGraficoLayout.setHorizontalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPGraficoLayout.setVerticalGroup(
            jPGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );

        jCBPortas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBPortas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBPortasItemStateChanged(evt);
            }
        });

        jCBBaudrates.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleBConexao.setText("Conectar");
        jToggleBConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBConexaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCBPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBBaudrates, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleBConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBBaudrates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleBConexao))
                    .addComponent(jBAjuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAjudaActionPerformed
        // TODO add your handling code here:
        new GuiAjuda().setVisible(true);
    }//GEN-LAST:event_jBAjudaActionPerformed

    private void jCBPortasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBPortasItemStateChanged
        // TODO add your handling code here:
        if(!jToggleBConexao.isSelected()){
            this.listaBaudrates = this.controleMonitor.getBaudrates("Não aolicavel");
            jCBBaudrates.removeAllItems();
            if(this.listaBaudrates != null){
                for(Integer baudrate: listaBaudrates){
                    jCBBaudrates.addItem(baudrate.toString());
                }
            }
        }
    }//GEN-LAST:event_jCBPortasItemStateChanged

    private void jToggleBConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBConexaoActionPerformed
        // TODO add your handling code here:
        Exception erro = null;
        if(jToggleBConexao.isSelected()){
            jToggleBConexao.setText("Desconectar");
            jCBPortas.setEnabled(false);
            jCBBaudrates.setEnabled(false);
            try {
                this.controleMonitor.startComunicacao((String)jCBPortas.getSelectedItem(),
                    Integer.parseInt((String)jCBBaudrates.getSelectedItem()), 0);
            } catch (NoSuchPortException ex) {
                erro = ex;
                Logger.getLogger(GuiMonitor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PortInUseException ex) {
                erro = ex;
                Logger.getLogger(GuiMonitor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (TooManyListenersException ex) {
                erro = ex;
                Logger.getLogger(GuiMonitor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedCommOperationException ex) {
                erro = ex;
                Logger.getLogger(GuiMonitor.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                if(erro != null){
                    jToggleBConexao.setSelected(false);
                    jToggleBConexao.setText("Conectar");
                    jCBPortas.setEnabled(true);
                    jCBBaudrates.setEnabled(true);
                }
            }
        }else{
            jToggleBConexao.setText("Conectar");
            jCBPortas.setEnabled(true);
            jCBBaudrates.setEnabled(true);
            this.controleMonitor.stopComunicacao();
        }
    }//GEN-LAST:event_jToggleBConexaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        // TODO add your handling code here:
//        this.controleMonitor = new ControleMonitor(this);
//        jCBPortas.removeAllItems();
//        jCBBaudrates.removeAllItems();
//        this.formWindowActivated(null);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(!jToggleBConexao.isSelected()){
            this.listaPortas = this.controleMonitor.getPortas();
            jCBPortas.removeAllItems();
            if(this.listaPortas != null){
                for(String porta: listaPortas){
                    if(porta!=null){
                        jCBPortas.addItem(porta);
                    }
                }
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.jToggleBConexao.setSelected(false);
        jToggleBConexaoActionPerformed(null);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAjuda;
    private javax.swing.JComboBox<String> jCBBaudrates;
    private javax.swing.JComboBox<String> jCBPortas;
    private javax.swing.JPanel jPGrafico;
    private javax.swing.JToggleButton jToggleBConexao;
    // End of variables declaration//GEN-END:variables
}
