/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MonitorSerial.Gui;

import MonitorSerial.Controle.ControleMonitor;
import MonitorSerial.Controle.ControleSerie;
import gnu.io.NoSuchPortException;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.util.TooManyListenersException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fmaia
 */
public class JFMonitorSerie extends javax.swing.JFrame {
    
    private ControleSerie controleSerie;
    private String[] listaPortas;
    /**
     * Creates new form JFMonitorSerie
     */
    public JFMonitorSerie(ControleSerie controleSerie) {
        this.controleSerie = controleSerie;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCBComConexao2 = new javax.swing.JComboBox<>();
        jCBBaundRateConexao2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTFNomeConexao2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBLinenBreak2 = new javax.swing.JCheckBox();
        jTBConexaoSerie = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jCBComConexao1 = new javax.swing.JComboBox<>();
        jCBBaundRateConexao1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTFNomeConexao1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBLinenBreak1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conexão em Serie");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Segunda Conexão"));

        jCBComConexao2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBComConexao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBComConexao2ActionPerformed(evt);
            }
        });

        jCBBaundRateConexao2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nome:");

        jLabel3.setText("Portas COMs");

        jLabel4.setText("Baund Rate");

        jCBLinenBreak2.setText("Enviar com \"\\n\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBLinenBreak2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCBBaundRateConexao2, 0, 150, Short.MAX_VALUE)
                        .addComponent(jCBComConexao2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jTFNomeConexao2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jCBComConexao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jCBBaundRateConexao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeConexao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBLinenBreak2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTBConexaoSerie.setText("Conectar");
        jTBConexaoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBConexaoSerieActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Primeira Conexão"));

        jCBComConexao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBComConexao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBComConexao1ActionPerformed(evt);
            }
        });

        jCBBaundRateConexao1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Nome:");

        jLabel8.setText("Portas COMs");

        jLabel9.setText("Baund Rate");

        jCBLinenBreak1.setText("Enviar com \"\\n\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBLinenBreak1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCBBaundRateConexao1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCBComConexao1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(jTFNomeConexao1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(jCBComConexao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(jCBBaundRateConexao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeConexao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBLinenBreak1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jTBConexaoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTBConexaoSerie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.jCBComConexao1.removeAllItems();
        this.jCBComConexao2.removeAllItems();
        this.jCBBaundRateConexao1.removeAllItems();
        this.jCBBaundRateConexao2.removeAllItems();
        this.formWindowActivated(null);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(!this.jTBConexaoSerie.isSelected()){
            this.listaPortas = this.controleSerie.getPortas();
            this.jCBComConexao1.removeAllItems();
            this.jCBComConexao2.removeAllItems();
            this.jCBBaundRateConexao1.removeAllItems();
            this.jCBBaundRateConexao2.removeAllItems();
            if(this.listaPortas != null){
                for(String p: this.listaPortas){
                    if(p!=null){
                        this.jCBComConexao1.addItem(p);
                    }
                }
                for(String p: this.listaPortas){
                    if(p!=null){
                        this.jCBComConexao2.addItem(p);
                    }
                }
            }
            
        }
    }//GEN-LAST:event_formWindowActivated

    private void jCBComConexao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBComConexao2ActionPerformed
        for(Integer b :this.controleSerie.getBaudrates((String)this.jCBComConexao2.getSelectedItem())){
            this.jCBBaundRateConexao2.addItem(b);
        }
        this.jTFNomeConexao2.setText((String)this.jCBComConexao2.getSelectedItem());
    }//GEN-LAST:event_jCBComConexao2ActionPerformed

    private void jTBConexaoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBConexaoSerieActionPerformed
        if(jTBConexaoSerie.isSelected()){
            if(!this.jCBComConexao1.getSelectedItem().equals(this.jCBComConexao2.getSelectedItem())){
                this.configurarTela(false);
                String nomePortas[]={(String)this.jCBComConexao1.getSelectedItem(),(String)this.jCBComConexao2.getSelectedItem()};
                Integer Baudrates[]={(Integer)this.jCBBaundRateConexao1.getSelectedItem(),(Integer)this.jCBBaundRateConexao2.getSelectedItem()};
                Integer timeouts[]={0,0};
                try {
                    this.controleSerie.startComunicacao(nomePortas, Baudrates, timeouts);
                } catch (NoSuchPortException ex) {
                    Logger.getLogger(JFMonitorSerie.class.getName()).log(Level.SEVERE, null, ex);
                } catch (PortInUseException ex) {
                    Logger.getLogger(JFMonitorSerie.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TooManyListenersException ex) {
                    Logger.getLogger(JFMonitorSerie.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedCommOperationException ex) {
                    Logger.getLogger(JFMonitorSerie.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Não é possivel conectar na mesma porta serial");
                this.configurarTela(true);
                jTBConexaoSerie.setSelected(false);
            }
        }else{
            this.controleSerie.stopComunicacao();
            this.configurarTela(true);
        }
    }//GEN-LAST:event_jTBConexaoSerieActionPerformed

    private void jCBComConexao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBComConexao1ActionPerformed
        for(Integer b :this.controleSerie.getBaudrates((String)this.jCBComConexao1.getSelectedItem())){
            this.jCBBaundRateConexao1.addItem(b);
        }
        this.jTFNomeConexao1.setText((String)this.jCBComConexao1.getSelectedItem());
    }//GEN-LAST:event_jCBComConexao1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.controleSerie.stopComunicacao();
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCBBaundRateConexao1;
    private javax.swing.JComboBox jCBBaundRateConexao2;
    private javax.swing.JComboBox<String> jCBComConexao1;
    private javax.swing.JComboBox<String> jCBComConexao2;
    private javax.swing.JCheckBox jCBLinenBreak1;
    private javax.swing.JCheckBox jCBLinenBreak2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jTBConexaoSerie;
    private javax.swing.JTextField jTFNomeConexao1;
    private javax.swing.JTextField jTFNomeConexao2;
    // End of variables declaration//GEN-END:variables

    private void configurarTela(Boolean boo){
        this.jCBComConexao1.setEnabled(boo);
        this.jCBComConexao2.setEnabled(boo);
        this.jCBBaundRateConexao1.setEnabled(boo);
        this.jCBBaundRateConexao2.setEnabled(boo);
        this.jTFNomeConexao1.setEnabled(boo);
        this.jTFNomeConexao2.setEnabled(boo);
        if(boo){
            jTBConexaoSerie.setText("Conectar");
        }else{
            jTBConexaoSerie.setText("Desconectar");
        }
    }
    
    public Boolean isSelectLinenBreak1(){
        return this.jCBLinenBreak1.isSelected();
    }
    
        public Boolean isSelectLinenBreak2(){
        return this.jCBLinenBreak2.isSelected();
    }

}
